spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=Vaibhav@04

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/ecommerce


keycloak.server-url=http://localhost:8180
keycloak.realm=ecommerce
keycloak.client-id=ecommerce-backend
keycloak.client-secret=hkmIs0yCAjOJ87H81XaZm7gTNNNwd37vpejzoxaWUOXjxX5aOSAOemjAFbLIx0oiKdCollzTH52jwfZ0O6hF2C

